### ISSUE TITLE
Provide custom request context

### ISSUE THREAD

**Issue by tigloo** [juancastillo0/graphql_server#17]
I'm building a GraphQL backend using Leto. Requests are authenticated using bearer tokens. The bearer token contains information about the client, for which I need to fetch context data (such as a user object, RBAC information) from the database.

I would like to add a request middleware that stores this information to the request context so that it only needs to be retrieved once, is stored in memory and every handler in the request pipeline can access it - essentially a Map<String,dynamic> that I could freely populate in Ctx.

Does something like this exist? Or an alternative method to achieve this?

**Comment by juancastillo0** [comment]
Hi! Thanks for the issue.

You can see a direct usage in this extension where the ref is [defined with a wrapper value](https://github.com/juancastillo0/leto/blob/8778144bce1ba0dbf65253ee1d78316d2162cbc1/leto/lib/src/extensions/persisted_queries.dart#L60C9-L62) (`MutableValue`, but can be anything) and we set de value like [this](https://github.com/juancastillo0/leto/blob/8778144bce1ba0dbf65253ee1d78316d2162cbc1/leto/lib/src/extensions/persisted_queries.dart#L155). The `MutableValue` will change for every request since the ref where it is saved is a `ScopedRef.local`.

I believe some of the complete examples do something like this for user or token data.

**Comment by tigloo** [comment]
This works, thanks!
